/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmk_wear_test_service_HealthDataConfig */

#ifndef _Included_com_gmk_wear_test_service_HealthDataConfig
#define _Included_com_gmk_wear_test_service_HealthDataConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    setDataCallback
 * Signature: (Lcom/gmk/wear/test/service/HealthDataCallback;)V
 */
JNIEXPORT void JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_setDataCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_init
  (JNIEnv *, jobject);

/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    openSensor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_openSensor
  (JNIEnv *, jobject);

/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_close
  (JNIEnv *, jobject);

/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    jniExit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_jniExit
  (JNIEnv *, jobject);

/*
 * Class:     com_gmk_wear_test_service_HealthDataConfig
 * Method:    checkLinkStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gmk_wear_test_service_HealthDataConfig_checkLinkStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
