# Uncomment this line to define a global platform for your project
# platform :ios, ‘6.0’
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'meizhikang' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'IHKeyboardAvoiding'
pod 'DZNEmptyDataSet'
pod 'JSONKit-NoWarning'
pod 'MJRefresh'
pod 'RBStoryboardLink'
pod 'ReactiveCocoa', '~> 2.5'
pod 'SWRevealViewController'
pod 'JSQMessagesViewController'
pod 'FSCalendar', :git => 'https://github.com/hxx0215/FSCalendar', :tag =>'1.7.0'
pod 'CocoaAsyncSocket'
end

