# Uncomment this line to define a global platform for your project
# platform :ios, ‘6.0’
source 'https://github.com/CocoaPods/Specs.git'

target 'meizhikang' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'IHKeyboardAvoiding'
pod 'DZNEmptyDataSet'
pod 'JSONKit-NoWarning'
pod 'MJRefresh'
pod 'RBStoryboardLink'
pod 'ReactiveCocoa', '~> 2.5'
pod 'SWRevealViewController'
pod 'JSQMessagesViewController'
end

